#!/usr/bin/env perl
use strict;
print "Content-type: text/html; charset=UTF-8\n\n";

print <<HEAD;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title>PIG - Perl Image-gallery Generator</title>
	<meta name="Author" content="Ævar Arnfjörð Bjarmason"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style type="text/css">
h1 {
	text-align:center;
	border: 1px solid black;
}
h1 em {
	font-weight: bold;
	text-decoration: normal;
	font-style: normal;
}
h1 em:after {
	content: " -";
}
address {
	margin-left: auto;
	margin-rigth: auto;
}
</style>
</head>
<body>

<h1><em>PIG</em> Perl Image-gallery Generator</h1>

<p>
	Perl Image-gallery Generator is a XHTML image gallery generator written in
	Perl, it aims for:
</p>

<ul>
	<li>Simplicity - It should not be complicated to run the program</li>
	<li>Portability - Have as small of a dependancy need as possible</li>
	<li>Integration - Have as small of a unique interface as possible, it
	should be easy to integrate the output into existing websites</li>
	<li></li>
</ul>
<p>
	Currently this is more than just design concepts, i already have a
	working <a href="http://www.simnet.is/velfag/sample/" title="Sample gallery">sample gallery</a>
	which was generated by <tt>PIG</tt> up and running, however there r
</p>

<address>
	<a href="http://developer.berlios.de" title="BerliOS Developer, Fostering Open Source Development">
		<img src="http://developer.berlios.de/bslogo.php?group_id=1727" width="124px" height="32px" border="0" alt="BerliOS Developer Logo">
	</a>
</address>
</body>
HEAD
